Redirect GitHub link to proper repository.
devarshishimpi/stonecss pull request #65
Opened 2022-10-15 20:11 UTC by Matthieu-ui

Link on landing page was for the archived repository!

2022-10-15 20:19 UTC, Matthieu-ui reviewed
fixed three links

2022-10-16 06:00 UTC, devarshishimpi requested changes
Could you add the blog link back?

2022-10-16 06:57 UTC, MrKrishnaAgarwal requested changes
@Matthieu-ui Please make the requested changes as mentioned below in comments.

2022-10-16 06:57 UTC, MrKrishnaAgarwal commented on index.html
> +
```suggestion
 <a href="https://blog.stonecss.com" target="_blank">Blog</a>
```

Please add these changes back.

2022-10-16 06:57 UTC, MrKrishnaAgarwal commented on index.html
> +                    <a href="https://github.com/devarshishimpi/stonecss" target="_blank">Github</a>
```suggestion
                    <a href="https://github.com/devarshishimpi/stonecss" target="_blank">Github</a>
                    <a href="https://blog.stonecss.com" target="_blank">Blog</a>
```
Please add the blog link here back too.

2022-10-16 07:27 UTC, MrKrishnaAgarwal approved these changes
Looks good now!

2022-10-16 07:27 UTC, devarshishimpi approved these changes

2022-10-16 07:28 UTC, merged